spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai
    username: postgres
    password: ${HETZNER_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

#OTHER
playwright:
  headless: true

scheduler:
  heatmap:
    cron: "0 */30 * * * *"
    save-to-target: false
  process-currencies: "0 0 8,16 * * *"
  low-price-alert: "0 15 21 ? * MON-SAT"
  owned-stock-alert: "0 15 8 ? * SAT"