spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

#OTHER
playwright:
  headless: true

scheduler:
  heatmap: "0 */5 * * * *"
  usdpln: "0 0 8,16 * * *"