spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai
    username: postgres
    password: ${HETZNER_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

#OTHER
playwright:
  headless: true

scheduler:
  heatmap: "0 */30 * * * *"
  usdpln: "0 0 8,16 * * *"
  low-price-alert: "0 15 21 ? * MON-SAT"