#SPRING
server:
  port: 1337

spring:
  application:
    name: SpringGPT

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ai
    username: postgres
    password: ${HETZNER_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

#OTHER
playwright:
  headless: true

mailgun:
  eu-base-url: https://api.eu.mailgun.net/
  api-key: ${MAILGUN_API_KEY}
  from: ${MAILGUN_FROM}
  domain: ${MAILGUN_DOMAIN}

alphavantage:
  url: https://www.alphavantage.co/query
  api-key: ${ALPHAVANTAGE_API_KEY}

twelvedata:
  url: https://api.twelvedata.com/
  api-key: ${TWELVEDATA_API_KEY}

scheduler:
  heatmap: "0 */30 * * * *"

logging:
  level:
    org.hibernate.orm.jdbc.bind: off
    org.springframework.boot: info